### ISSUE TITLE
Run setup.sh have some error

### ISSUE THREAD

**Issue by Edwin737** [intel/iotg-yocto-bsp-public#12]
Hi I Run setup.sh  from iotg-yocto-bsp has some error as below
I use Ubuntu 14.04 to run 
 -------------------------------------------------------------------------------------------------------------
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/asd/yocto_build/bitbake/lib/bb/daemonize.py", line 87, in createDaemon
    function()
  File "/home/asd/yocto_build/bitbake/lib/bb/server/process.py", line 459, in _startServer
    self.cooker = bb.cooker.BBCooker(self.configuration, self.featureset)
  File "/home/asd/yocto_build/bitbake/lib/bb/cooker.py", line 199, in __init__
    self.initConfigurationData()
  File "/home/asd/yocto_build/bitbake/lib/bb/cooker.py", line 364, in initConfigurationData
    self.databuilder.parseBaseConfiguration()
  File "/home/asd/yocto_build/bitbake/lib/bb/cookerdata.py", line 307, in parseBaseConfiguration
    raise bb.BBHandledException
bb.BBHandledException
WARNING: Duplicate inclusion for /home/asd/yocto_build/meta/conf/distro/include/security_flags.inc in /home/asd/yocto_build/meta-poky/conf/distro/poky.conf
ERROR: The following required tools (as specified by HOSTTOOLS) appear to be unavailable in PATH, please install them in order to proceed:
  git-lfs

Entering build status checker ...
./setup.sh: line 300: cd: ../yocto_build/build/tmp/deploy/images/intel-corei7-64/: No such file or directory
BSP Build: FAILED!!!
HDDIMG was not generated!
Please check the build log for detailed failure.
-------------------------------------------------------------------------------------------------------------
I try to run  sudo apt-get install git-lfs but still have some problem as below

asd@asd-desktop:~/iotg-yocto-bsp-public$ sudo apt-get install git-lfs
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package git-lfs

Could you help me??

**Comment by baliset2010** [comment]
Hi,

I had the same problem.

Try download git-lfs-linux-amd64-X.X.X.tar.gz from git-lfs.github.com, 
extract it and run install.sh.  It fixed in my case.
